import test from 'node:test'
import assert from 'node:assert/strict'
import { timingConfig, validDate, shiftDate, planDates } from '../lib/production-timing.mjs'
test('date-only timing handles weekends, leap years and invalid inputs', () => {
  assert.equal(shiftDate('2026-09-04', 1, 'business'), '2026-09-07')
  assert.equal(shiftDate('2026-09-07', -1, 'business'), '2026-09-04')
  assert.equal(shiftDate('2026-09-04', 1, 'calendar'), '2026-09-05')
  assert.equal(shiftDate('2028-02-28', 1), '2028-02-29')
  assert.equal(validDate('2026-02-29'), false)
  assert.throws(() => timingConfig({ turnaround_days: 1.5 }))
  assert.throws(() => timingConfig({ enabled: 'true' }))
  assert.throws(() => timingConfig({ production_date: '2026-02-30' }))
  const tasks = [{ timing: JSON.stringify({due_offset:-2}) }, {timing:JSON.stringify({due_date:'2026-09-08',due_offset:1})}]
  const plan = planDates({ enabled:true,start_date:'2026-09-04',turnaround_days:5 }, tasks)
  assert.equal(plan.planned_production_date,'2026-09-11')
  assert.equal(plan.tasks[0].planned_due_date,'2026-09-09')
  assert.equal(plan.tasks[1].planned_due_date,'2026-09-08')
  assert.equal(planDates({enabled:false},tasks).tasks[1].planned_due_date,null)
})
test('reusable timing snapshots, rush overrides, optional scheduling, revision conflicts and calendar filters', async () => {
  process.env.PSC_DB=':memory:'
  const { getDb, run, initDb, setSetting } = await import('../lib/db.mjs')
  const p = await import('../lib/production.mjs')
  const { productionCalendar } = await import('../lib/production-calendar.mjs')
  const db = getDb()
  run("INSERT INTO contacts(id,name) VALUES(1,'Timing sample')")
  run("INSERT INTO jobs(id,contact_id,job_number,title,stage,status,created_at) VALUES(1,1,'T-1','Untimed','new','active','2026-09-04 09:00:00')")
  initDb(db)
  assert.equal(p.workflow(1).revision,0)
  const steps=[{title:'Burn screens',department:'Prepress',stage:'prepress',due_offset:-2,assigned_id:7},{title:'Print',department:'Production',stage:'production',due_offset:0}]
  const members=[{id:7,status:'active'}]
  const t=p.saveTemplate(null,{name:'Timed screen',match_text:'timed screen',steps,timing:{enabled:true,turnaround_days:5,day_basis:'business'}},members)
  let w=p.applyWorkflow(1,{revision:0,template_ids:[t.id]},'Manager')
  assert.equal(w.timing.planned_production_date,'2026-09-11')
  assert.equal(w.tasks[0].planned_due_date,'2026-09-09')
  p.saveTemplate(t.id,{...t,timing:{enabled:true,turnaround_days:9}},members)
  assert.equal(p.workflow(1).timing.turnaround_days,5)
  w=p.editTask(1,w.tasks[0].id,{...w.tasks[0],revision:w.revision,due_date:'2026-09-08'},'Manager',members)
  w=p.saveJobTiming(1,{revision:w.revision,timing:{...w.timing,production_date:'2026-09-07'},reason:'Rush'},'Manager')
  assert.equal(w.tasks[0].planned_due_date,'2026-09-08')
  assert.equal(w.tasks[1].planned_due_date,'2026-09-07')
  assert.throws(()=>p.saveJobTiming(1,{revision:1,timing:{}},'Manager'),/changed/)
  let cal=productionCalendar({start:'2026-09-01',end:'2026-09-30',department:'Prepress',mine:true,memberId:7})
  assert.equal(cal.events.filter(e=>e.kind==='task').length,1)
  assert.equal(productionCalendar({start:'2026-09-01',end:'2026-09-30',mine:true,memberId:9}).events.length,0)
  assert.throws(()=>productionCalendar({start:'2026-01-01',end:'2026-12-31'}),/range/)
  w=p.saveJobTiming(1,{revision:w.revision,timing:{...w.timing,enabled:false}},'Manager')
  assert.equal(w.tasks[0].planned_due_date,null)
  assert.equal(productionCalendar({start:'2026-09-01',end:'2026-09-30'}).unscheduled_count,1)
  // Future dates do not gate completion. Enabling/disabling does not change task order.
  w=p.saveJobTiming(1,{revision:w.revision,timing:{...w.timing,enabled:true,production_date:'2099-01-01'}},'Manager')
  w=p.transitionTask(1,w.tasks[0].id,{revision:w.revision,action:'complete'},{manager:true,name:'Manager'})
  assert.equal(w.tasks[0].status,'done')
  setSetting('production_auto','1')
  run("INSERT INTO jobs(id,contact_id,job_number,title,decoration,stage,status,created_at) VALUES(2,1,'T-2','Automatic','timed screen','new','active','2026-09-04 09:00:00')")
  assert.equal(p.workflow(2).timing.turnaround_days,9)
  assert.equal(p.workflow(2).tasks[0].due_offset,-2)
  const before = JSON.stringify(p.workflow(2)); initDb(db); assert.equal(JSON.stringify(p.workflow(2)),before)
  // Planning can be added before choosing a task template.
  run("INSERT INTO jobs(id,contact_id,job_number,title,stage,status) VALUES(3,1,'T-3','Calendar first','new','active')")
  let pre=p.saveJobTiming(3,{revision:0,timing:{enabled:true,production_date:'2026-09-15'}},'Manager')
  assert.doesNotThrow(() => p.guardWorkflowStage(3,'production'))
  pre=p.applyWorkflow(3,{revision:pre.revision,template_ids:[t.id]},'Manager')
  assert.equal(pre.timing.planned_production_date,'2026-09-15')
})
