import test from 'node:test'
import assert from 'node:assert/strict'
test('Slack operator binds employees, preserves conversation, gates writes and refuses duplicate/stale work',async()=>{
  process.env.PSC_DB=':memory:'
  const db=await import('../lib/db.mjs'), p=await import('../lib/production.mjs'), op=await import('../lib/slack-operator.mjs')
  let members=[{id:1,name:'Manager',role:'owner',status:'active'},{id:2,name:'QC',role:'staff',status:'active'}]
  db.setSetting('slack_team_id','TTEST')
  assert.throws(()=>op.saveOperatorConfig({enabled:true,mode:'auto',links:[{user_id:'UBAD',member_id:9}]},members))
  op.saveOperatorConfig({enabled:true,mode:'review',links:[{user_id:'UOWNER',member_id:1},{user_id:'USTAFF',member_id:2}]},members)
  db.run("INSERT INTO contacts(id,name) VALUES(1,'Test')")
  db.run("INSERT INTO jobs(id,job_number,title,contact_id,status,stage) VALUES(1,'JOB-1001','Wildcats',1,'active','new')")
  const template=p.saveTemplate(null,{name:'Simple',steps:[{title:'Check print',department:'QC',stage:'qc',assigned_id:2}]},members)
  let w=p.applyWorkflow(1,{revision:0,template_ids:[template.id]},'Manager')
  let n=0,quotes=0
  const deps={tenantKey:'test',members:()=>members,planner:async()=>({text:'{"action":"help"}'}),quote:async()=>{quotes++;return{ok:true,pieces:48,total:480,estimate:{id:77,estimate_number:'EST-77'}}}}
  const call=(message,extra={})=>op.operatorMessage({team_id:'TTEST',user_id:'UOWNER',channel:'C1',thread:'1.1',request_id:'req'+(++n),message,...extra},deps)
  assert.match((await call('job JOB-1001',{team_id:'TOTHER'})).reply,/link your Slack/)
  assert.match((await call('job JOB-1001',{user_id:'UNKNOWN'})).reply,/link your Slack/)
  assert.match((await call('job JOB-1001')).reply,/Task \d+: Check print/)
  let r=await call('quote 48 navy tees 2 color front')
  assert.equal(quotes,0)
  const code=r.reply.match(/confirm ([a-f0-9]{8})/)[1]
  assert.match((await call('confirm '+code,{user_id:'USTAFF'})).reply,/does not match/)
  r=await call('confirm '+code,{request_id:'quote-confirm'})
  assert.equal(quotes,1);assert.match(r.reply,/EST-77/)
  assert.deepEqual(await call('confirm '+code,{request_id:'quote-confirm'}),r)
  assert.equal(quotes,1)
  r=await call(`complete task ${w.tasks[0].id} on JOB-1001`,{user_id:'USTAFF'})
  const completeCode=r.reply.match(/confirm ([a-f0-9]{8})/)[1]
  w=p.saveJobTiming(1,{revision:w.revision,timing:{enabled:true,production_date:'2026-09-20'}},'Manager')
  assert.match((await call('confirm '+completeCode,{user_id:'USTAFF'})).reply,/changed/)
  assert.equal(p.workflow(1).tasks[0].status,'pending')
  op.saveOperatorConfig({...op.operatorConfig(members),enabled:true,mode:'auto'},members)
  assert.match((await call('schedule JOB-1001 2026-09-15',{user_id:'USTAFF'})).reply,/manager is needed/)
  assert.match((await call(`complete task ${w.tasks[0].id} on JOB-1001`,{user_id:'USTAFF'})).reply,/Artwork approval required/)
  db.run('UPDATE jobs SET art_approved_at=? WHERE id=1',db.now())
  assert.match((await call(`complete task ${w.tasks[0].id} on JOB-1001`,{user_id:'USTAFF'})).reply,/completed Check print/)
  assert.equal(p.workflow(1).tasks[0].status,'done')
  members=members.map(m=>m.id===2?{...m,status:'inactive'}:m)
  assert.match((await call('my tasks',{user_id:'USTAFF'})).reply,/link your Slack/)
  const planned=await op.planOperator('make that 96',[{role:'user',text:'quote 48 navy tees'}],async()=>({text:'{"action":"quote","text":"quote 900 invented hoodies"}'}))
  assert.equal(planned.text,'96 navy tees')
  const {parseIntakeHeuristic}=await import('../lib/ai.mjs')
  assert.equal(parseIntakeHeuristic(planned.text).total_pieces,96)
  assert.equal((await op.planOperator('make that 96',[{role:'user',text:'quote 48 navy tees, 24 S 24 M'}])).action,'clarify')
  assert.equal((await op.planOperator('change the color to red',[{role:'user',text:'quote 48 navy tees'}],async()=>({text:'{"action":"quote","text":"quote 900 invented hoodies"}'}))).action,'clarify')
  const {quickQuote}=await import('../lib/quickquote.mjs')
  let emitted=0;db.onContactCreated(()=>emitted++)
  const before=db.get('SELECT count(*) n FROM contacts').n
  await assert.rejects(()=>quickQuote({text:'quote 24 tees one color front',contact_email:'revoked@example.test',beforeCommit:()=>{throw Error('Revoked')}}),/Revoked/)
  assert.equal(db.get('SELECT count(*) n FROM contacts').n,before)
  const draft=await quickQuote({text:planned.text+' 2 color front',contact_email:'new@example.test',emitAutomation:false})
  assert.equal(draft.pieces,96);assert.equal(draft.estimate.status,'draft');assert.equal(emitted,0)
  await quickQuote({text:'quote 24 tees one color front',contact_email:'legacy@example.test'})
  assert.equal(emitted,1)
  assert.equal((await op.planOperator('refund everything',[],async()=>({text:'{"action":"delete_all"}'}))).action,'help')
  db.run("INSERT INTO slack_operator_requests(request_id,thread_key,status,created_at) VALUES('interrupted','old','running',?)",db.now())
  assert.match((await call('quote 20 tees',{request_id:'interrupted'})).reply,/already started/)
  assert.equal(quotes,1)
})
